import createClient from "openapi-fetch";
import type { paths } from "./types"; // generated by openapi-typescript

export const client = createClient<paths>({
  baseUrl: "http://localhost:5186/",
});

// Example usage:
// const { data, error } = await client.GET("/blogposts/{post_id}", {
//   params: {
//     path: { post_id: "my-post" },
//     query: { version: 2 },
//   },
// });

// const { data, error } = await client.PUT("/blogposts", {
//   body: {
//     title: "New Post",
//     body: "<p>New post body</p>",
//     publish_date: new Date("2023-03-01T12:00:00Z").getTime(),
//   },
// });
